[book]
authors = ["GutenAIR Team"]
language = "es"
src = "src"
title = "Documentacion de GutenAIR"

[output.html]
git-repository-url = "https://github.com/pedro/GutenAIR"
site-url = "/GutenAIR-gtk4/"
